package com.omrbranch.baseClass;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

public class Hotel {
	public static void main(String[] args) throws InterruptedException {
		
		WebDriver driver = new ChromeDriver();
		driver.get("https://omrbranch.com/");
		driver.manage().window().maximize();
		WebElement email = driver.findElement(By.id("email"));
		email.sendKeys("harikaransrinivasan172000@gmail.com");
		WebElement pass = driver.findElement(By.id("pass"));
		pass.sendKeys("Greens@1234");
		WebElement clkbtn = driver.findElement(By.xpath("//button[@value='login']"));
		clkbtn.click();
		driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
		WebElement prtUname = driver.findElement(By.xpath("//a[@data-testid='username']"));
		String Uname = prtUname.getText();
		System.out.println(Uname);
		WebElement exp = driver.findElement(By.xpath("//h5[@class='font35 font-weight-bold text-white mb-4']"));
		String priexp = exp.getText();
		System.out.println(priexp);
		WebElement state = driver.findElement(By.id("state"));
		Select s = new Select(state);
		s.selectByVisibleText("Andhra Pradesh");
		WebElement sltCity = driver.findElement(By.id("city"));
		Select c = new Select(sltCity);
		c.selectByValue("Tirupati");
		WebElement sltRoom = driver.findElement(By.id("room_type"));
		Select rm = new Select(sltRoom);
		rm.selectByIndex(1);
		rm.selectByIndex(2);
		rm.selectByIndex(3);
		rm.selectByIndex(4);
		rm.selectByIndex(5);
		WebElement chk = driver.findElement(By.xpath("(//div[@class='inout-control col-md-3'])[1]"));
		chk.click();
		WebElement date = driver.findElement(By.xpath("(//a[@class='ui-state-default'])[1]"));
		date.click();
		WebElement co = driver.findElement(By.xpath("(//div[@class='inout-control col-md-3'])[2]"));
		co.click();
		WebElement codate = driver.findElement(By.xpath("(//a[@class='ui-state-default'])[3]"));
		codate.click();
		WebElement roomnos = driver.findElement(By.id("no_rooms"));
		Select rn = new Select(roomnos);
		rn.selectByIndex(1);
		WebElement adult = driver.findElement(By.id("no_adults"));
		Select ad = new Select(adult);
		ad.selectByIndex(2);
		WebElement child = driver.findElement(By.id("no_child"));
		child.sendKeys("2");
		driver.switchTo().frame(0);
		WebElement search = driver.findElement(By.xpath("//button[@class='btn filter_btn']"));
		search.click();
		driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
		WebElement prht = driver.findElement(By.xpath("//h5[@class='font35 font-weight-bold mb-4']"));
		String htp = prht.getText();
		System.out.println(htp);
		WebElement prtHotelName = driver.findElement(By.xpath("(//h5[contains(text(),'Resort')])[1]"));
		String phn = prtHotelName.getText();
		System.out.println(phn);
		WebElement clkCont = driver.findElement(By.xpath("(//a[@class='btn filter_btn'])[1]"));
		clkCont.click();
		Alert al =driver.switchTo().alert();
		al.accept();
		WebElement clkformine = driver.findElement(By.id("own"));
		clkformine.click();
		WebElement mr = driver.findElement(By.id("user_title"));
		Select sms = new Select(mr);
		sms.selectByIndex(1);
		WebElement entername = driver.findElement(By.id("first_name"));
		entername.sendKeys("Harikaran");
		WebElement enterlname = driver.findElement(By.id("last_name"));
		enterlname.sendKeys("Srinivasan");
		WebElement enterMno = driver.findElement(By.id("user_phone"));
		enterMno.sendKeys("9080277916");
		WebElement enterMail = driver.findElement(By.id("user_email"));
		enterMail.sendKeys("harikaransrinivasan172000@gmail.com");
		WebElement clkgst = driver.findElement(By.id("gst"));
		clkgst.click();
		WebElement entGST = driver.findElement(By.id("gst_registration"));
		entGST.sendKeys("9043592058");
		WebElement entCMP = driver.findElement(By.id("company_name"));
		entCMP.sendKeys("Greens Tech OMR Branch");
		WebElement entADD = driver.findElement(By.id("company_address"));
		entADD.sendKeys("Thoraipakkam");
		WebElement clknxt = driver.findElement(By.id("step1next"));
		clknxt.click();
		WebElement early = driver.findElement(By.id("early"));
		early.click();
		WebElement addData = driver.findElement(By.id("other_request"));
		addData.sendKeys("need hygine room");
		WebElement clkNT = driver.findElement(By.id("step2next"));
		clkNT.click();
		WebElement clkCard = driver.findElement(By.xpath("//div[@class='credit-card pm']"));
		clkCard.click();
		WebElement PT = driver.findElement(By.id("payment_type"));
		Select Ptype = new Select(PT);
		Ptype.selectByIndex(1);
		WebElement CT= driver.findElement(By.id("card_type"));
		Select Ctype = new Select(CT);
		Ctype.selectByIndex(1);
		WebElement CNO = driver.findElement(By.id("card_no"));
		CNO.sendKeys("5555555555552222");
		WebElement CName = driver.findElement(By.id("card_name"));
		CName.sendKeys("Harikaran");
		WebElement clkMon = driver.findElement(By.id("card_month"));
		Select CMon = new Select(clkMon);
		CMon.selectByIndex(5);
		WebElement selectyear = driver.findElement(By.id("card_year"));
		Select yr = new Select(selectyear);
		yr.selectByIndex(3);
		WebElement cvv = driver.findElement(By.id("cvv"));
		cvv.sendKeys("768");
		WebElement clBTN = driver.findElement(By.id("submitBtn"));
		clBTN.click();
		driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
		WebElement prtorder = driver.findElement(By.xpath("//h2[@name='booking-code']"));
		String op = prtorder.getText();
		System.out.println(op);
		WebElement againHN = driver.findElement(By.xpath("//strong[contains(text(),'Resort')]"));
		String AHN = againHN.getText();
		System.out.println(AHN);
		WebElement FHN = driver.findElement(By.xpath("//p[contains(text(),'Hotel ')]"));
		String OFHN = FHN.getText();
		System.out.println(OFHN);
		WebElement clACC = driver.findElement(By.xpath("//a[@data-testid='username']"));
		clACC.click();
		WebElement clMY = driver.findElement(By.xpath("//a[contains(text(),'My Account')]"));
		clMY.click();
		driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
		WebElement pbk = driver.findElement(By.xpath("//h4[contains(text(),'Bookings')]"));
		String opbk = pbk.getText();
		System.out.println(opbk); //#ZRDUY71287
		WebElement soid = driver.findElement(By.xpath("//input[@name='search']"));
		soid.sendKeys("#ZRDUY71287");
		WebElement againpoid = driver.findElement(By.xpath("//span[contains(text(),'#ZRDU')]"));
		String text = againpoid.getText();
		System.out.println(text);
		WebElement againhotel = driver.findElement(By.xpath("(//h5[contains(text(),'Resort')])[3]"));
		String text2 = againhotel.getText();
		System.out.println(text2);
		WebElement element = driver.findElement(By.xpath("(//strong[@class='total-prize'])[3]"));
		String text3 = element.getText();
		System.out.println(text3);
		WebElement edit = driver.findElement(By.xpath("(//button[@type='submit'])[4]"));
		edit.click();
		driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
		WebElement mcid = driver.findElement(By.xpath("//input[@name='check_in']"));
		mcid.click();
		WebElement clmc = driver.findElement(By.xpath("//a[contains(text(),'27')]"));
		clmc.click();
		WebElement confirm = driver.findElement(By.xpath("(//button[@type='submit'])[1]"));
		confirm.click();
		WebElement success = driver.findElement(By.xpath("//li[@class='alertMsg']"));
		String text4 = success.getText();
		System.out.println(text4);
		driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
		WebElement MYA = driver.findElement(By.xpath("//a[@data-testid='username']"));
		MYA.click();
		WebElement IMYA = driver.findElement(By.xpath("//a[contains(text(),'My Account')]"));
		IMYA.click();
		WebElement PrintBook= driver.findElement(By.xpath("//h4[contains(text(),'Bookings')]"));
		String text5 = PrintBook.getText();
		System.out.println(text5);
		WebElement Ragainpoid = driver.findElement(By.xpath("//span[contains(text(),'#ZRDU')]"));
		String Rtext = Ragainpoid.getText();
		System.out.println(Rtext);
		WebElement Ragainhotel = driver.findElement(By.xpath("(//h5[contains(text(),'Resort')])[3]"));
		String Rtext2 = Ragainhotel.getText();
		System.out.println(Rtext2);
		WebElement Relement = driver.findElement(By.xpath("(//strong[@class='total-prize'])[3]"));
		String Rtext3 = Relement.getText();
		System.out.println(Rtext3);
		WebElement cl = driver.findElement(By.xpath("(//a[contains(text(),'Cancel')])[9]"));
		cl.click();
		Alert a = driver.switchTo().alert();
		a.accept();
		driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
		WebElement finals = driver.findElement(By.xpath("//li[contains(text(),'Your')]"));
		String ft = finals.getText();
		System.out.println(ft);
		
		
	}

}
